### ISSUE TITLE
Using vue-function-api in a new project

### ISSUE THREAD

**Issue by afattahi54** [vuejs/vue-function-api#30]
We are new in vue and we want start a new project in next three months. Well we want to make sure that we are choosing the best environment which will be compatible with Vue future development path. And we want to be Vue3 compatible (as much as possible).

According to this plugin and a complete description at [related rfc](https://github.com/vuejs/rfcs/blob/function-apis/active-rfcs/0000-function-api.md) , the next VueJs movement will be toward function API and the Class API RFC is moved a way.

So using Typescript in a vue project ( for example sample mentioned at https://sobolevn.me/2019/06/really-typing-vue ) will not be a good idea.
Am I correct ?

Is it recommended to use function api and typescript together? And is there any sample which can help to get start.

PS: I have read this comment some where (Vue@3 will have improved typescript support), is it still correct?!

**Comment by beeplin** [comment]
Please read https://github.com/vuejs/rfcs/blob/function-apis/active-rfcs/0000-function-api.md ;)

**Comment by SilentDepth** [comment]
> So using Typescript in a vue project will not be a good idea. Am I correct?

It's hard to say (at this moment). The post you linked is mostly talking about Vue 2, but Vue 3 will be a different story. I believe Vue 3 will be better than ever, however I cannot give you any evidence on that. Obviously there are still months for us to see the progress of Vue 3 development, and anything could happen.

> Is it recommended to use function api and typescript together?

Yes. One of the goals of Function API proposal is to provide a better compatibility with TypeScript (than the abandoned Class API Proposal).

> I have read this comment some where (Vue@3 will have improved typescript support), is it still correct?!

Definitely yes.

**Comment by posva** [comment]
Using Typescript for a project seems like a good idea if you want that typing. You can also opt-out of TS whenever needed, so you can apply it only to your business logic. It's true that the function api solves many of the existing problems today with Typescript and Vue. So it's up to you to use it or not for your components

Regarding using Vue-function-api for your app, you don't need to. Vue 3 will also support the object syntax. You can use this if you want to experience with a slightly different way of thinking. It may indeed make things easier to migrate to the final function api in Vue 3 but **you don't need to write your components that way for Vue 3**, it's an optional advanced feature

There was a prototype that allowed to move from the object syntax to the function api one but it's not public yet since the RFC hasn't been merged yet which means we are still discussing some last bits of it before saying _this is the way we will go_

**Comment by MatanYadaev** [comment]
@posva What's the difference between function API and composition API?
Why here the docs is about `reactive` method and in this repo is `value`? https://vue-composition-api-rfc.netlify.com/

**Comment by posva** [comment]
it's the same. It's all part of an evolving RFC, names changed, this lib adapted the names very recently in the v3. This library is meant to allow people use the new syntax before it's available in Vue 3
